
// server environment PRODUCTION or DEVELOPEMENT

export const SERVER_ENVIRONMENT='DEVELOPEMENT';

// server IP
export var SERVER_IP='';
const DEVELOPEMENT_SERVER_IP='http://127.0.0.1:3000';
const PRODUCTION_SERVER_IP='http://127.0.0.1:5000';

if(SERVER_ENVIRONMENT=='DEVELOPEMENT')
{
      SERVER_IP=DEVELOPEMENT_SERVER_IP;
}
else
{
      SERVER_IP=PRODUCTION_SERVER_IP;
}


// product list
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

// product details
export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='PRODUCT_DETAILS_FAIL';

// create product
export const CREATE_PRODUCT_REQUEST='CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS='CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL='CREATE_PRODUCT_FAIL';


// update product
export const UPDATE_PRODUCT_REQUEST='UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL='UPDATE_PRODUCT_FAIL';

// delete product

export const DELETE_PRODUCT_REQUEST='DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL='DELETE_PRODUCT_FAIL';

// cart
export const ADD_ITEM_TO_CART='ADD_ITEM_TO_CART';
export const CART_REMOVE_ITEM='CART_REMOVE_ITEM';

// sign in
export const SIGN_IN_REQUEST='SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS='SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL='SIGN_IN_FAIL';


// sign up
export const SIGN_UP_REQUEST='SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS='SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL='SIGN_UP_FAIL';


// Authorization
export const Authorization={Authorization:'Bearer '};